### ISSUE TITLE
'utf8' codec can't decode byte 0xfe in position 77: invalid start byte

### ISSUE THREAD

**Issue by brian-bason** [brian-bason/docker-build-tool#12]
The following error is being thrown when trying to execute the build tool with this [docker-build.yml](https://github.com/brian-bason/docker-build-tool/files/429209/docker-build.txt) file

```
2016-08-22 10:54:16 - Unexpected error during build due to error : 'utf8' codec can't decode byte 0xfe in position 77: invalid start byte
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/docker_build/__main__.py", line 757, in main
    not command_line_args.keep_containers
  File "/usr/local/lib/python2.7/site-packages/docker_build/__main__.py", line 418, in _build
    show_logs=True
  File "/usr/local/lib/python2.7/site-packages/docker_build/__main__.py", line 275, in _run_command
    execute_instructions(instructions, environment_variables, console_log)
  File "/usr/local/lib/python2.7/site-packages/docker_build/__main__.py", line 240, in execute_instructions
    user="root"
  File "/usr/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker/api/exec_api.py", line 35, in exec_create
    res = self._post_json(url, data=data)
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 198, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfe in position 77: invalid start byte
```

**Comment by brian-bason** [comment]
This issue is related to the fact that Arguments defined as Obfuscated were not really base64 encoded. When the tool tried to decode them an invalid value was created thus causing the above error.

A check should be included to indicate the problem before getting to the RUN command which caused the container to fail as invalid character were being passed.
