### ISSUE TITLE
AttributeError: 'module' object has no attribute ‘InvalidDockerBuildConfigFile'

### ISSUE THREAD

**Issue by brian-bason** [brian-bason/docker-build-tool#26]
InvalidDockerBuildConfigFile exception is not a valid exception and it is causing an error when there is an error in the build configuration.

```
Unexpected error during build due to error : 'module' object has no attribute 'InvalidDockerBuildConfigFile'
Traceback (most recent call last):
  File "/Users/brian/Dev/Code/docker-build/docker_build/__main__.py", line 615, in main
    not command_line_args.keep_containers
  File "/Users/brian/Dev/Code/docker-build/docker_build/__main__.py", line 405, in _build
    build_context_populated = _copy_build_context(docker_client, container_id, step_config)
  File "/Users/brian/Dev/Code/docker-build/docker_build/__main__.py", line 365, in _copy_build_context
    raise exception.InvalidDockerBuildConfigFile(
AttributeError: 'module' object has no attribute ‘InvalidDockerBuildConfigFile'
```

**Comment by brian-bason** [comment]
Fixed as part of #27, the ticket will be closed without any commits against it.
