### ISSUE TITLE
Failure when trying to pull images during build

### ISSUE THREAD

**Issue by brian-bason** [brian-bason/docker-build-tool#34]
The following error is being thrown when an image is pulled down during a build process.

```
Unexpected error during build due to error : Extra data: line 2 column 1 - line 12 column 1 (char 71 - 781)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/docker_build/__main__.py", line 635, in main
    not command_line_args.keep_containers
  File "/Library/Python/2.7/site-packages/docker_build/__main__.py", line 422, in _build
    container_id = _create_container(docker_client, from_image)
  File "/Library/Python/2.7/site-packages/docker_build/__main__.py", line 158, in _create_container
    container = create_container_with_auto_pull()
  File "/Library/Python/2.7/site-packages/docker_build/__main__.py", line 152, in create_container_with_auto_pull
    _pull_image(docker_client, image)
  File "/Library/Python/2.7/site-packages/docker_build/__main__.py", line 107, in _pull_image
    details = json.loads(output)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 12 column 1 (char 71 - 781)
```

**Comment by johndavidpearce** [comment]
Looks like this is a JSON error, the tool is failing to read the response from the Docker Daemon after a pull.
