### ISSUE TITLE
Bug: docker-py errors being suppressed with wrong error message

### ISSUE THREAD

**Issue by johndavidpearce** [brian-bason/docker-build-tool#35]
There are cases where the docker build tool is hiding the real error message as reported by the `docker-py` module, and is actually reporting the wrong (and misleading) error message. An example follows.

Assuming your docker server version is `1.11.1`, if you install the latest `docker-build-tool` version then you will automatically get `docker-py` version `1.10.2`. Unfortunately this version of `docker-py` is not compatible with the docker server version (however, this is a separate issue). When you now run `docker-build` you get output like:

```
$ docker-build
Starting new container from '<some container>'
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

Running the docker client CLI reveals this is not the case:

```
$ docker create '<some container>'
<container hash>
```

So connection to the daemon is not the problem. After investigation, we commented out `__main__.py:649` and replaced it with `raise`. This yielded the real exception:

```
$ docker-build
Starting new container from '<image>'
Traceback (most recent call last):
  File "/Users/marija/Documents/Ops/docker-build-tool/venv/bin/docker-build", line 9, in <module>
    load_entry_point('docker-build-tool==0.11.1', 'console_scripts', 'docker-build')()
  File "/Users/marija/Documents/Ops/docker-build-tool/docker_build/__main__.py", line 635, in main
    not command_line_args.keep_containers
  File "/Users/marija/Documents/Ops/docker-build-tool/docker_build/__main__.py", line 422, in _build
    container_id = _create_container(docker_client, from_image)
  File "/Users/marija/Documents/Ops/docker-build-tool/docker_build/__main__.py", line 141, in _create_container
    details = _inspect_image(docker_client, image)
  File "/Users/marija/Documents/Ops/docker-build-tool/docker_build/__main__.py", line 72, in _inspect_image
    details = docker_client.inspect_image(image)
  File "/usr/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker/api/image.py", line 136, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 171, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 167, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.24, server API version: 1.23)")
```

The correct behaviour of `docker-build-tool` in this circumstance is to simply report the error message as given by `docker-py`:

```
client is newer than server (client API version: 1.24, server API version: 1.23)
```

**Comment by johndavidpearce** [comment]
Please note this ticket is not to address the specific docker version problem mentioned above, but it is a bug around the build tool suppressing error messages returned from the Docker client.

I suspect #25 is also a sufferer from this 'hiding error messages' problem.
